version: '2'
services:
  db:
    image: postgres
    volumes:
      - ./bmi-calculator-db:/var/lib/postgresql/data

  back:
    build: bmi-calculator-back
    image: yovasx2/bmi-calculator-back
    volumes:
      - ./bmi-calculator-back:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
  
  front:
    build: bmi-calculator-front
    image: yovasx2/bmi-calculator-front
    volumes:
      - ./bmi-calculator-front:/app
      - /app/node_modules # node_modules disappear between builds
    ports:
      - "4200:4200"
